### ISSUE TITLE
Migrate to Vert.x 3.6.2

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-dependencies#17]
Vert.x 3.6 introduces both security fixes and new features.
https://vertx.io/blog/eclipse-vert-x-3-6-0-released/

**Describe the solution you'd like**
Analyze and define tasks to upgrade Knot.x modules.

**Additional context**
We need to validate `Web API gateways` section - how it fits to Knot.x Open API integration.

**Comment by malaskowski** [comment]
Migrated to `3.6.3`
