### ISSUE TITLE
Dependency mockito-all is deprecated

### ISSUE THREAD

**Issue by tMaxx** [Knotx/knotx-dependencies#5]
### Rationale

Artifact `org.mockito:mockito-all` was deprecated/abandoned, in favor of `org.mockito:mockito-core`. Last update was 2.0.2-beta back in 2015, while the newest version of `mockito-core` is 2.21 from July 2018.

This move would also allow the use of `mockito-junit-jupiter`, which is necessary for transition of Knot.x core to JUnit 5.

### Possible incompatibilites

This change will be backwards-compatible **per Knot.x module** - modules that use `mockito-all` will continue working. Switching requires developer intervention anyway. Switching Knot.x core may break *a lot of things*.

References:
- https://github.com/mockito/mockito
- https://search.maven.org/search?q=g:org.mockito
- https://search.maven.org/search?q=a:mockito-all
- https://github.com/mockito/mockito/issues/324

<sub>Creating this ticket so the whole problem desn't get lost/abandoned/forgotten. Part of Cognifide/knotx#417.</sub>

**Comment by malaskowski** [comment]
`mockito-all` is not used by any Knot.x module - closing
